data:extend({
  {
    type = "item",
    name = "biomass",
    icon = kr_items_with_variations_icons_path .. "biomass/biomass.png",
    icon_size = 64,
    icon_mipmaps = 4,
    pictures = {
      {
        size = 64,
        filename = kr_items_with_variations_icons_path .. "biomass/biomass.png",
        scale = 0.25,
        mipmap_count = 4,
      },
      {
        size = 64,
        filename = kr_items_with_variations_icons_path .. "biomass/biomass-1.png",
        scale = 0.25,
        mipmap_count = 4,
      },
      {
        size = 64,
        filename = kr_items_with_variations_icons_path .. "biomass/biomass-2.png",
        scale = 0.25,
        mipmap_count = 4,
      },
      {
        size = 64,
        filename = kr_items_with_variations_icons_path .. "biomass/biomass-3.png",
        scale = 0.25,
        mipmap_count = 4,
      },
    },
    fuel_category = "chemical",
    fuel_value = "2MJ",
    fuel_emissions_multiplier = 0.8,
    fuel_acceleration_multiplier = 0.8,
    fuel_top_speed_multiplier = 0.8,
    flags = { "always-show" },
    subgroup = "raw-material",
    order = "a[biomass]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "kr-note-1",
    icon = kr_items_icons_path .. "note.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "other",
    flags = { "hidden" },
    stack_size = 50,
  },
  ---
  {
    type = "item",
    name = "kr-void",
    icon = kr_items_icons_path .. "void.png",
    flags = { "hidden" },
    icon_size = 64,
    icon_mipmaps = 4,
    order = "zzz[kr-void]",
    stack_size = 999,
  },
  {
    type = "item",
    name = "pollution-filter",
    icon = kr_items_icons_path .. "pollution-filter.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "intermediate-product",
    order = "w2-a1[pollution-filter]",
    stack_size = 50,
  },
  {
    type = "item",
    name = "used-pollution-filter",
    icon = kr_items_icons_path .. "used-pollution-filter.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "intermediate-product",
    order = "w2-a2[used-pollution-filter]",
    stack_size = 50,
  },
  {
    type = "item",
    name = "improved-pollution-filter",
    icon = kr_items_icons_path .. "improved-pollution-filter.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "intermediate-product",
    order = "w2-b1[improved-pollution-filter]",
    stack_size = 50,
  },
  {
    type = "item",
    name = "used-improved-pollution-filter",
    icon = kr_items_icons_path .. "used-improved-pollution-filter.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "intermediate-product",
    order = "w2-b2[used-improved-pollution-filter]",
    stack_size = 50,
  },
  {
    type = "item",
    name = "empty-dt-fuel",
    icon = kr_items_icons_path .. "empty-dt-fuel.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "intermediate-product",
    order = "r[uranium-processing]-b1[dt-fuel]-a1[empty-dt-fuel]",
    stack_size = 10,
  },
  {
    type = "item",
    name = "dt-fuel",
    icon = kr_items_icons_path .. "dt-fuel.png",
    icon_size = 64,
    icon_mipmaps = 4,
    pictures = {
      layers = {
        {
          size = 64,
          filename = kr_items_icons_path .. "dt-fuel.png",
          scale = 0.25,
          mipmap_count = 4,
        },
        {
          draw_as_light = true,
          flags = { "light" },
          size = 64,
          filename = kr_items_icons_path .. "dt-fuel-light.png",
          scale = 0.25,
          mipmap_count = 4,
        },
      },
    },
    fuel_category = "fusion-fuel",
    fuel_value = "10GJ",
    burnt_result = "empty-dt-fuel",
    subgroup = "intermediate-product",
    order = "r[uranium-processing]-b1[dt-fuel]-a2[dt-fuel]",
    stack_size = 10,
  },
  ---
  {
    type = "item",
    name = "matter-stabilizer",
    icon = kr_items_icons_path .. "matter-stabilizer.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "intermediate-product",
    order = "w1[matter-stabilizers]-a1[matter-stabilizer]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "charged-matter-stabilizer",
    icon = kr_items_icons_path .. "charged-matter-stabilizer.png",
    icon_size = 64,
    icon_mipmaps = 4,
    pictures = {
      layers = {
        {
          size = 64,
          filename = kr_items_icons_path .. "charged-matter-stabilizer.png",
          scale = 0.25,
          mipmap_count = 4,
        },
        {
          draw_as_light = true,
          flags = { "light" },
          size = 64,
          filename = kr_items_icons_path .. "charged-matter-stabilizer-light.png",
          scale = 0.25,
          mipmap_count = 4,
        },
      },
    },
    subgroup = "intermediate-product",
    order = "w1[matter-stabilizers]-a2[charged-matter-stabilizer]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "matter-cube",
    icon = kr_items_icons_path .. "matter-cube.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "intermediate-product",
    order = "000[matter]-000[matter-cube]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "empty-antimatter-fuel-cell",
    icon = kr_items_icons_path .. "empty-antimatter-fuel-cell.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "intermediate-product",
    order = "r[uranium-processing]-b2[antimatter-fuel-cell]-a1[empty-antimatter-fuel-cell]",
    stack_size = 10,
  },
  {
    type = "item",
    name = "charged-antimatter-fuel-cell",
    icon = kr_items_icons_path .. "charged-antimatter-fuel-cell.png",
    icon_size = 64,
    icon_mipmaps = 4,
    pictures = {
      layers = {
        {
          size = 64,
          filename = kr_items_icons_path .. "charged-antimatter-fuel-cell.png",
          scale = 0.25,
          mipmap_count = 4,
        },
        {
          draw_as_light = true,
          flags = { "light" },
          size = 64,
          filename = kr_items_icons_path .. "charged-antimatter-fuel-cell-light.png",
          scale = 0.25,
          mipmap_count = 4,
        },
      },
    },
    fuel_category = "antimatter-fuel",
    fuel_value = "300GJ",
    burnt_result = "empty-antimatter-fuel-cell",
    subgroup = "intermediate-product",
    order = "r[uranium-processing]-b2[antimatter-fuel-cell]-a2[charged-antimatter-fuel-cell]",
    stack_size = 10,
  },
})
